import { NextResponse } from 'next/server';
import { db } from '@/lib/firebaseAdmin';

export const dynamic = 'force-dynamic';

const historicalData = [
  { "date": "2026-05-07T16:18:52.000Z", "order_number": "4631", "status": "Completed", "customer": "Robert Taylor", "customer_type": "New", "products": "1× The Authority Builder", "items_sold": 1, "net_sales": 750, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-04-23T14:38:23.000Z", "order_number": "4626", "status": "Completed", "customer": "Gloria Betancourt", "customer_type": "Returning", "products": "1× Financial Systems Migration & Integration Suite", "items_sold": 1, "net_sales": 680, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-04-13T17:45:35.000Z", "order_number": "4616", "status": "Completed", "customer": "Luis Luna", "customer_type": "Returning", "products": "1× Domain Name Annual Registration", "items_sold": 1, "net_sales": 28, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-04-10T13:55:41.000Z", "order_number": "4611", "status": "Completed", "customer": "Unknown", "customer_type": "New", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 86, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-02-22T22:31:46.000Z", "order_number": "4330", "status": "Completed", "customer": "Heidy", "customer_type": "New", "products": "1× The Authority Builder", "items_sold": 1, "net_sales": 1000, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-02-20T03:36:31.000Z", "order_number": "4326", "status": "Completed", "customer": "Amy Garcia", "customer_type": "Returning", "products": "1× Basic Website", "items_sold": 1, "net_sales": 270, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-02-06T22:23:51.000Z", "order_number": "4264", "status": "Completed", "customer": "Amy Garcia", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription, 1× Basic Website, 1× Professional Custom Brochure Design", "items_sold": 4, "net_sales": 270, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-02-03T23:13:56.000Z", "order_number": "4245", "status": "Completed", "customer": "Luis Herrador", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 105, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-02-03T02:06:58.000Z", "order_number": "4250", "status": "Completed", "customer": "Carlos Diaz del Valle", "customer_type": "Returning", "products": "1× The Authority Builder", "items_sold": 1, "net_sales": 680, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-01-26T20:43:56.000Z", "order_number": "4228", "status": "Completed", "customer": "Juan C. Lopez", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-01-13T23:34:20.000Z", "order_number": "4232", "status": "Completed", "customer": "Sheila Suders", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 128, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-01-13T14:22:15.000Z", "order_number": "4227", "status": "Completed", "customer": "Jorge Siwady", "customer_type": "Returning", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-01-09T17:34:54.000Z", "order_number": "4224", "status": "Completed", "customer": "Gloria Betancourt", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2026-01-02T19:34:48.000Z", "order_number": "4208", "status": "Completed", "customer": "Michelle Andrade", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-12-17T21:58:56.000Z", "order_number": "4218", "status": "Completed", "customer": "Ricardo Riedel", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-11-26T23:08:34.000Z", "order_number": "4198", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× Android App Development", "items_sold": 1, "net_sales": 700, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-11-25T20:18:11.000Z", "order_number": "4188", "status": "Completed", "customer": "Leda Duron", "customer_type": "Returning", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 105, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-11-08T17:23:26.000Z", "order_number": "4190", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× The Growth Partner", "items_sold": 1, "net_sales": 460, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-10-31T00:23:46.000Z", "order_number": "4184", "status": "Completed", "customer": "Jorge Lanza", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-10-29T14:09:58.000Z", "order_number": "4187", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 80, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-10-03T20:47:57.000Z", "order_number": "4179", "status": "Completed", "customer": "Roger Miranda", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 105, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-09-23T20:41:11.000Z", "order_number": "4181", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× The Growth Partner, 1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 3, "net_sales": 460, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-07-22T15:17:23.000Z", "order_number": "4002", "status": "Completed", "customer": "David Ernesto Lopez", "customer_type": "New", "products": "1× Standard Website Change", "items_sold": 1, "net_sales": 75, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-06-27T14:11:16.000Z", "order_number": "3988", "status": "Completed", "customer": "Jorge Siwady", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 168, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-06-10T19:25:18.000Z", "order_number": "3977", "status": "Completed", "customer": "David Yanez", "customer_type": "New", "products": "3× Domain Name Annual Registration", "items_sold": 3, "net_sales": 75, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-06-10T19:20:21.000Z", "order_number": "3967", "status": "Completed", "customer": "Luis Herrador", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 115, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-05-06T20:56:07.000Z", "order_number": "3966", "status": "Completed", "customer": "Gloria Betancourt", "customer_type": "Returning", "products": "1× Standard ERP Customization", "items_sold": 1, "net_sales": 50, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-05-06T17:34:42.000Z", "order_number": "3972", "status": "Completed", "customer": "Michelle Andrade", "customer_type": "New", "products": "1× Basic Website", "items_sold": 1, "net_sales": 400, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-04-22T21:01:32.000Z", "order_number": "3957", "status": "Completed", "customer": "Belkis Pineda", "customer_type": "New", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-04-01T14:31:15.000Z", "order_number": "3961", "status": "Completed", "customer": "Luis Luna", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 105, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-03-24T21:33:08.000Z", "order_number": "3952", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-02-09T01:31:30.000Z", "order_number": "3358", "status": "Completed", "customer": "Jorge Lanza", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 80, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-01-14T16:38:38.000Z", "order_number": "3357", "status": "Completed", "customer": "Sheila Suders", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-01-13T21:01:58.000Z", "order_number": "3356", "status": "Completed", "customer": "Gloria Betancourt", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-01-06T02:51:40.000Z", "order_number": "3354", "status": "Completed", "customer": "Juan C. Lopez", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 115, "coupons": "-", "attribution": "Web admin" },
  { "date": "2025-01-05T05:48:26.000Z", "order_number": "3353", "status": "Completed", "customer": "Jorge Siwady", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-12-24T02:02:04.000Z", "order_number": "3348", "status": "Completed", "customer": "Pumas FC Soccer Academy", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-12-14T04:58:25.000Z", "order_number": "3339", "status": "Completed", "customer": "Ricardo Riedel", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 109, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-11-10T14:00:19.000Z", "order_number": "3331", "status": "Completed", "customer": "Jorge Lanza", "customer_type": "Returning", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 80, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-10-31T16:51:02.000Z", "order_number": "3330", "status": "Completed", "customer": "Leda Duron", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 120, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-09-28T22:03:49.000Z", "order_number": "3323", "status": "Completed", "customer": "Jorge Lanza", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 80, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-09-27T03:38:56.000Z", "order_number": "3326", "status": "Completed", "customer": "Jorge Siwady", "customer_type": "Returning", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 155, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-09-26T16:42:29.000Z", "order_number": "3324", "status": "Completed", "customer": "Roger Miranda", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 110, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-08-24T19:10:57.000Z", "order_number": "3293", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "Returning", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 80, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-04-11T18:25:34.000Z", "order_number": "3179", "status": "Completed", "customer": "Ricardo Riedel", "customer_type": "Returning", "products": "1× The Growth Partner", "items_sold": 1, "net_sales": 100, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-03-14T16:43:11.000Z", "order_number": "3175", "status": "Completed", "customer": "Ricardo Riedel", "customer_type": "Returning", "products": "1× The Growth Partner", "items_sold": 1, "net_sales": 100, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-27T12:20:06.000Z", "order_number": "3174", "status": "Completed", "customer": "Carlos Diaz del Valle", "customer_type": "Returning", "products": "Legacy Charge", "items_sold": 1, "net_sales": 0.5, "coupons": "-", "attribution": "Unknown" },
  { "date": "2024-02-26T19:55:10.000Z", "order_number": "3173", "status": "Completed", "customer": "Navneet Kalra", "customer_type": "New", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration, 1× The Growth Partner", "items_sold": 3, "net_sales": 450, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-26T17:48:45.000Z", "order_number": "3100", "status": "Completed", "customer": "Janeth Garcia", "customer_type": "Returning", "products": "1× The Growth Partner", "items_sold": 1, "net_sales": 305, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-20T14:30:09.000Z", "order_number": "3051", "status": "Completed", "customer": "Jorge Lanza", "customer_type": "New", "products": "1× Webhosting Annual Subscription, 1× Basic Website", "items_sold": 2, "net_sales": 390, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-09T16:45:38.000Z", "order_number": "3022", "status": "Completed", "customer": "Luis Herrador", "customer_type": "New", "products": "2× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 3, "net_sales": 150, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-08T20:30:33.000Z", "order_number": "3054", "status": "Completed", "customer": "Ricardo Riedel", "customer_type": "New", "products": "1× The Growth Partner", "items_sold": 1, "net_sales": 100, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-07T14:11:10.000Z", "order_number": "3076", "status": "Completed", "customer": "Janeth Garcia", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 105, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-02-05T18:18:33.000Z", "order_number": "3034", "status": "Completed", "customer": "Pumas FC Soccer Academy", "customer_type": "New", "products": "1× Social Media Starter Kit", "items_sold": 1, "net_sales": 150, "coupons": "-", "attribution": "Web admin" },
  { "date": "2024-01-23T14:33:36.000Z", "order_number": "2741", "status": "Completed", "customer": "Juan C. Lopez", "customer_type": "New", "products": "1× Webhosting Annual Subscription", "items_sold": 1, "net_sales": 119, "coupons": "-", "attribution": "Unknown" },
  { "date": "2024-01-16T18:41:27.000Z", "order_number": "2742", "status": "Completed", "customer": "Jorge Siwady", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Unknown" },
  { "date": "2024-01-12T14:15:41.000Z", "order_number": "2718", "status": "Completed", "customer": "Sheila Suders", "customer_type": "New", "products": "1× Basic Website, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 195, "coupons": "-", "attribution": "Unknown" },
  { "date": "2024-01-11T18:32:20.000Z", "order_number": "2712", "status": "Completed", "customer": "Gloria Betancourt", "customer_type": "New", "products": "1× Webhosting Annual Subscription, 1× Domain Name Annual Registration", "items_sold": 2, "net_sales": 145, "coupons": "-", "attribution": "Unknown" },
  { "date": "2023-09-28T21:55:59.000Z", "order_number": "2552", "status": "Completed", "customer": "Roger Miranda", "customer_type": "New", "products": "1× Domain Name Annual Registration, 1× Webhosting Annual Subscription", "items_sold": 2, "net_sales": 64, "coupons": "-", "attribution": "Unknown" }
];

export async function GET() {
  try {
    let imported = 0;
    // Map through the array and send each row to Firestore
    for (const record of historicalData) {
      // Skipping the refunded test order with no number
      if (record.status.toLowerCase() !== 'completed') continue;
      
      await db.collection('sales').add(record);
      imported++;
    }

    return NextResponse.json({ 
      success: true, 
      message: `Successfully imported ${imported} legacy WooCommerce records to Firestore!` 
    });
  } catch (error: any) {
    console.error('Import Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}